window.portfolioProjects = [
  {
    id: 'employee-goal-management-portal',
    category: 'built',
    title: 'Employee Goal Management Portal',
    shortTitle: 'Employee Goals',
    description: 'A MERN-based portal for goal setting, approvals, performance tracking, audit logs, user administration, role-based access, and report exports.',
    thumbnailLabel: 'Goal Tracking Dashboard',
    tech: ['MongoDB', 'Express', 'React', 'Node.js', 'JWT', 'CSV/Excel'],
    video: './public/videos/employee-goal-management-demo.mp4',
    live: 'https://employee-management-0cu9.onrender.com/',
    repo: 'https://github.com/anshikaaa1911/Employee-Management',
    overview: 'A role-aware employee goal management application designed to help teams define, review, approve, and track measurable goals from one dashboard.',
    problem: 'Teams often track goals across disconnected spreadsheets and messages, making approvals, accountability, and progress history difficult to manage.',
    objective: 'Create a centralized workflow where employees, managers, and admins can manage goals with clear permissions, status tracking, and exportable reports.',
    solution: 'Built a MERN workflow with authentication, protected routes, goal lifecycle states, audit visibility, and structured data export support.',
    impact: 'Improves transparency, reduces manual follow-up, and gives managers a cleaner view of goal ownership and progress.',
    features: ['Role-based login and protected routes', 'Goal creation, review, approval, and progress tracking', 'Audit logs and administrative controls', 'CSV and Excel report exports'],
    screenshots: ['Goals dashboard', 'Approval workflow', 'Admin user controls'],
    technical: {
      frontend: 'React interface with reusable views for dashboards, goal forms, tables, and role-specific actions.',
      backend: 'Node.js and Express REST APIs with JWT authentication and authorization middleware.',
      database: 'MongoDB collections for users, goals, status history, and audit-style records.',
      apis: 'REST endpoints for authentication, goal lifecycle operations, user management, and exports.',
      ml: 'No machine learning layer; the project focuses on workflow automation and access control.'
    },
    challenges: ['Designing clean role boundaries without duplicating dashboard logic.', 'Keeping goal status transitions predictable across employee, manager, and admin flows.'],
    future: ['Add analytics dashboards for goal completion trends.', 'Add notifications and reminders for pending approvals.', 'Introduce richer performance insights by team and time period.']
  },
  {
    id: 'college-marketplace-recommendation-system',
    category: 'built',
    title: 'College Marketplace with Recommendation System',
    shortTitle: 'College Marketplace',
    description: 'A peer-to-peer student resale platform with recommendation logic to improve product discovery from user behavior and listing data.',
    thumbnailLabel: 'Student Marketplace',
    tech: ['JavaScript', 'Recommendation System', 'HTML', 'CSS', 'Data Preprocessing'],
    video: './public/videos/college-marketplace-demo.mp4',
    live: 'https://inshivank.github.io/College-Market-Place/',
    repo: 'https://github.com/inshivank/College-Market-Place',
    overview: 'A student-focused marketplace that helps campus users buy, sell, and discover relevant products more easily.',
    problem: 'Students need a trusted, campus-centered resale experience where relevant listings are easy to find without scrolling through unrelated items.',
    objective: 'Build a lightweight marketplace experience and improve discovery with recommendation-driven product surfacing.',
    solution: 'Created product listing flows, category browsing, and recommendation-oriented discovery patterns based on available product and interaction signals.',
    impact: 'Makes student resale more approachable and improves the chances that users find useful items quickly.',
    features: ['Student product listing cards', 'Category-based browsing', 'Recommendation-oriented product discovery', 'Responsive marketplace layout'],
    screenshots: ['Marketplace home', 'Product listing cards', 'Recommended products'],
    technical: {
      frontend: 'HTML, CSS, and JavaScript interface optimized for simple static deployment.',
      backend: 'Static-hosted project flow; backend behavior is represented through client-side logic.',
      database: 'Structured product data used by the marketplace UI and recommendation flow.',
      apis: 'Client-side data access patterns for listings and recommendations.',
      ml: 'Recommendation approach based on listing attributes and user-oriented discovery signals.'
    },
    challenges: ['Balancing simple static deployment with a marketplace-style user experience.', 'Designing useful recommendations with limited interaction data.'],
    future: ['Add authentication and seller profiles.', 'Persist product data with a backend database.', 'Improve recommendations with collaborative filtering as usage data grows.']
  },
  {
    id: 'behavioral-fraud-awareness-platform',
    category: 'built',
    title: 'Behavioral Fraud Awareness & Simulation Platform',
    shortTitle: 'Fraud Awareness',
    description: 'An interactive cyber fraud simulation platform using deep learning concepts to classify scam patterns and improve user awareness.',
    thumbnailLabel: 'Fraud Simulation Lab',
    tech: ['Deep Learning', 'CNN', 'XceptionNet', 'Cybersecurity', 'Python'],
    video: './public/videos/behavioral-fraud-awareness-demo.mp4',
    live: '#',
    repo: 'https://github.com/anshikaaa1911/Behavioral-Fraud-Awareness---Simulation-Platform',
    overview: 'A simulation platform that teaches users to recognize suspicious digital behavior through scenario-based fraud awareness.',
    problem: 'Users are frequently exposed to phishing, impersonation, and scam patterns but often lack safe, realistic practice environments.',
    objective: 'Create an educational platform that combines interactive scam scenarios with model-backed classification concepts.',
    solution: 'Developed simulations around fraud patterns and incorporated CNN/XceptionNet-oriented classification ideas for scam awareness.',
    impact: 'Supports safer digital behavior by making fraud cues more visible, memorable, and practice-driven.',
    features: ['Fraud scenario simulations', 'Awareness-focused learning flow', 'Scam classification concept', 'User-friendly cyber safety interface'],
    screenshots: ['Scenario simulation', 'Fraud classification', 'Awareness feedback'],
    technical: {
      frontend: 'Interactive web interface for fraud scenarios, prompts, and feedback states.',
      backend: 'Application logic supporting scenario flow and result handling.',
      database: 'Scenario and content data structured around fraud categories.',
      apis: 'Endpoints or application functions for scenario playback and classification feedback.',
      ml: 'CNN-based deep learning approach with XceptionNet concepts for scam and fraud pattern classification.'
    },
    challenges: ['Turning cybersecurity risk into understandable user-facing simulations.', 'Connecting model concepts to educational feedback without overwhelming users.'],
    future: ['Add more scam categories and adaptive difficulty.', 'Track awareness progress over time.', 'Expand model evaluation with larger labeled datasets.']
  },
  {
    id: 'grownet-trust-community-platform',
    category: 'building',
    title: 'GROWNET Trust-Based Community Platform',
    shortTitle: 'GROWNET',
    description: 'A scalable community platform concept with trust scoring, SOS alerts, and recommendation features for safer local interaction.',
    thumbnailLabel: 'Trust Community Network',
    tech: ['Trust Scoring', 'Recommendations', 'Safety Workflows', 'Scalable Design'],
    video: '',
    live: '#',
    repo: 'https://github.com/anshikaaa1911/GROWNET-Trust-Based-Community-Platform',
    overview: 'GROWNET is being designed as a trust-based community platform for safer, more reliable local collaboration and support.',
    problem: 'Community platforms can struggle with trust, safety, and relevance, especially when users need urgent help or reliable recommendations.',
    objective: 'Design a community system that uses trust indicators, safety features, and recommendations to strengthen user confidence.',
    solution: 'Planned architecture includes trust scoring, SOS workflows, community recommendations, and scalable moderation patterns.',
    impact: 'Aims to make community interaction safer, more accountable, and easier to navigate.',
    features: ['Currently building trust score logic', 'Planned SOS alert workflows', 'Community recommendation system', 'Scalable moderation and safety model'],
    planned: ['Trust-based user profiles', 'SOS and emergency support flow', 'Recommendation engine for posts or community needs', 'Moderation and reporting tools'],
    screenshots: ['Trust profile concept', 'SOS flow concept', 'Community feed concept'],
    technical: {
      frontend: 'Planned responsive dashboard for feed, trust profiles, alerts, and community actions.',
      backend: 'Planned service layer for users, trust scores, alerts, moderation, and recommendations.',
      database: 'Planned schema for profiles, posts, ratings, trust signals, and event logs.',
      apis: 'Planned REST APIs for community actions, trust updates, alert creation, and recommendations.',
      ml: 'Potential recommendation and trust-ranking algorithms based on user behavior, ratings, and safety signals.'
    },
    challenges: ['Designing trust scoring that is useful without becoming unfair or opaque.', 'Making safety workflows fast while preserving verification and accountability.'],
    future: ['Pilot the trust model with real community scenarios.', 'Add explainable trust indicators.', 'Scale alerts and recommendations with stronger ranking algorithms.']
  },
  {
    id: 'handwriting-ocr-system',
    category: 'building',
    title: 'Handwriting OCR System',
    shortTitle: 'Handwriting OCR',
    description: 'A computer vision and OCR system for extracting readable text from handwritten or scanned document images.',
    thumbnailLabel: 'OCR Extraction Workspace',
    tech: ['Computer Vision', 'OCR', 'OpenCV', 'Tesseract', 'Python'],
    video: '',
    live: '#',
    repo: 'https://github.com/anshikaaa1911/HandWriting',
    overview: 'An OCR system in progress for converting handwritten or printed text from images into machine-readable output.',
    problem: 'Handwritten notes and scanned documents are difficult to search, analyze, and reuse when they remain trapped in image form.',
    objective: 'Build a preprocessing and OCR pipeline that improves text extraction quality from imperfect images.',
    solution: 'Planned system uses image preprocessing, thresholding, noise reduction, segmentation, and OCR extraction workflows.',
    impact: 'Can reduce manual transcription effort and create a base for searchable document processing.',
    features: ['Currently building OCR pipeline', 'Image preprocessing workflow', 'Text extraction and cleanup', 'Document digitization interface'],
    planned: ['Image upload and preview', 'Noise reduction and threshold controls', 'OCR confidence review', 'Export to editable text formats'],
    screenshots: ['Image upload concept', 'Preprocessing preview', 'Extracted text output'],
    technical: {
      frontend: 'Planned interface for upload, preview, OCR results, and text correction.',
      backend: 'Planned Python processing service for image preprocessing and OCR execution.',
      database: 'Optional storage for uploaded documents, extracted text, and processing metadata.',
      apis: 'Planned endpoints for image upload, OCR processing, and result retrieval.',
      ml: 'OCR pipeline using OpenCV preprocessing and Tesseract, with room for handwritten recognition models as the dataset grows.'
    },
    challenges: ['Handling inconsistent handwriting, image noise, shadows, and skew.', 'Choosing preprocessing steps that improve extraction without damaging useful characters.'],
    future: ['Add handwriting-specific recognition models.', 'Add confidence highlighting and manual correction tools.', 'Support batch document processing.']
  }
];
